// Generated by CoffeeScript 1.9.1
'use strict';
var express, router;

express = require('express');

router = express.Router();

router.get('/', function(req, res, next) {
  return res.render('chat');
});

module.exports = router;
